name: Docker Image CI

on:
  push:
    # branches: [ "main" ]
    # tags: [ "*" ]
  pull_request:
    branches: [ "main" ]
    tags: [ "*" ]
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          VERSION="${{ github.event.release.tag_name }}"
        elif [ "${{ github.ref_type }}" = "tag" ]; then
          VERSION="${{ github.ref_name }}"
        else
          VERSION="latest"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag htcondor-ce/htcondor-ce:$VERSION 
